var enlocale = {
        "locale": "en-US",
        "date": {
            "dateFormats": {
                "shortDate": "d/MM/yyyy",
                "shortTime": "h:mm tt",
                "longDate": "dddd, MMMM dd, yyyy",
                "longTime": "h:mm:ss tt",
                "dayMonth": "d/MM",
                "yearMonth": "MMMM, yyyy",
                "full": "dddd, MMMM dd, yyyy h:mm:ss tt"
            },
            "months": {
                "narrow": [
                    "J",
                    "F",
                    "M",
                    "A",
                    "M",
                    "J",
                    "J",
                    "A",
                    "S",
                    "O",
                    "N",
                    "D"
                ],
                "short": [
                    "Jan",
                    "Feb",
                    "Mar",
                    "Apr",
                    "May",
                    "Jun",
                    "Jul",
                    "Aug",
                    "Sep",
                    "Oct",
                    "Nov",
                    "Dec"
                ],
                "long": [
                    "January",
                    "February",
                    "March",
                    "April",
                    "May",
                    "June",
                    "July",
                    "August",
                    "September",
                    "October",
                    "November",
                    "December"
                ]
            },
            "days": {
                "narrow": [
                    "S",
                    "M",
                    "T",
                    "W",
                    "T",
                    "F",
                    "S"
                ],
                "short": [
                    "Sun",
                    "Mon",
                    "Tue",
                    "Wed",
                    "Thu",
                    "Fri",
                    "Sat"
                ],
                "long": [
                    "Sunday",
                    "Monday",
                    "Tuesday",
                    "Wednesday",
                    "Thursday",
                    "Friday",
                    "Saturday"
                ]
            },
            "dayPeriods": {
                "am": "AM",
                "pm": "PM"
            },
            "firstDayOfWeek": 0
        },
        "strings": {
            "newFormHeader": "New Appointment",
            "editFormHeader": "Edit Appointment",
            "newRecurrenceFormHeader": "New Recurrence",
            "editRecurrenceFormHeader": "Edit Recurrence",
            "cueFormHeader": "Cue items",
            "dateCaption": "Date",
            "datesCaption": "Dates",
            "subjectCaption": "Subject",
            "startTimeCaption": "Start time",
            "endTimeCaption": "End time",
            "allDayEventCaption": "All day event",
            "reminderCaption": "Reminder",
            "detailsCaption": "Details",
            "contactsCaption": "Contacts",
            "todayCaption": "Today",
            "locationCaption": "Location",
            "patternCaption": "Pattern",
            "rangeCaption": "Range of recurrence",
            "everyCaption": "Every",
            "ofEveryCaption": "of every",
            "startCaption": "Start",
            "noEndCaption": "No end date",
            "endAfterCaption": "End after",
            "endDateCaption": "End by",
            "saveButtonCaption": "Save",
            "optionsButtonCaption": "Options",
            "cancelButtonCaption": "Cancel",
            "recurrenceButtonCaption": "Recurrence",
            "deleteButtonCaption": "Delete",
            "secondsValue": "seconds",
            "minuteValue": "minute",
            "minutesValue": "minutes",
            "hourValue": "hour",
            "hoursValue": "hours",
            "dayValue": "day",
            "daysValue": "days",
            "weeksValue": "weeks",
            "monthValue": "month",
            "dailyValue": "Daily",
            "weeklyValue": "Weekly",
            "monthlyValue": "Monthly",
            "yearlyValue": "Yearly",
            "intervalValue": "By time interval",
            "firstValue": "first",
            "secondValue": "second",
            "thirdValue": "third",
            "fourthValue": "fourth",
            "lastValue": "last",
            "weekendValue": "weekend",
            "weekdayValue": "weekday",
            "recurrenceDailyOnePattern": "Occurs every day",
            "recurrenceDailyTwoPattern": "Occurs every [Days] days",
            "recurrenceDailyThreePattern": "Occurs every weekday",
            "recurrenceDailyFourPattern": "Occurs every weekend day",
            "recurrenceWeeklyOnePattern": "Occurs every [DaysOfWeek]",
            "recurrenceWeeklyTwoPattern": "Occurs every [Weeks] weeks on [DaysOfWeek]",
            "recurrenceMonthlyOnePattern": "Occurs day [DayOfMonth] of every [Months] month(s)",
            "recurrenceMonthlyTwoPattern": "Occurs the [Occurrence] [Day] of every [Months] month(s)",
            "recurrenceYearlyOnePattern": "Occurs every [MonthOfYear] [DayOfMonth]",
            "recurrenceYearlyTwoPattern": "Occurs the [Occurrence] [Day] of [MonthOfYear]",
            "recurrenceIntervalPattern": "Occurs every [Interval.Days] days [Interval.Hours] hours [Interval.Minutes] minutes [Interval.Seconds] seconds",
            "recurrenceStartDatePattern": "effective [StartDate]",
            "recurrenceEndDatePattern": "until [EndDate]",
            "recurrenceTimeOnePattern": "from [StartTime] to [EndTime]",
            "recurrenceTimeTwoPattern": "at [StartTime]"
        }
    }