var rulocale =  {
    "locale": "ru-RU",
    "date": {
        "dateFormats": {
            "shortDate": "dd.MM.yyyy",
            "shortTime": "H:mm",
            "longDate": "d MMMM y г.",
            "longTime": "H:mm:ss",
            "dayMonth": "dd.MM",
            "yearMonth": "MMMM, yyyy",
            "full": "d MMMM y г. H:mm:ss"
        },
        "months": {
            "narrow": [
                "Я",
                "Ф",
                "М",
                "А",
                "М",
                "И",
                "И",
                "А",
                "С",
                "О",
                "Н",
                "Д"
            ],
            "short": [
                "янв.",
                "фев.",
                "март",
                "апр.",
                "май",
                "июнь",
                "июль",
                "авг.",
                "сент.",
                "окт.",
                "нояб.",
                "дек."
            ],
            "long": [
                "Январь",
                "Февраль",
                "Март",
                "Апрель",
                "Май",
                "Июнь",
                "Июль",
                "Август",
                "Сентябрь",
                "Октябрь",
                "Ноябрь",
                "Декабрь"
            ]
        },
        "days": {
            "narrow": [
                "в",
                "п",
                "в",
                "с",
                "ч",
                "п",
                "с"
            ],
            "short": [
                "вс",
                "пн",
                "вт",
                "ср",
                "чт",
                "пт",
                "сб"
            ],
            "long": [
                "воскресенье",
                "понедельник",
                "вторник",
                "среда",
                "четверг",
                "пятница",
                "суббота"
            ]
        },
        "dayPeriods": {
            "am": "",
            "pm": ""
        },
        "firstDayOfWeek": 1
    },
    "strings": {
        "newFormHeader": "Мероприятие",
        "editFormHeader": "Мероприятие - изменить",
        "newRecurrenceFormHeader": "Повторение",
        "editRecurrenceFormHeader": "Повторение - изменить",
        "cueFormHeader": "Скрытые мероприятия",
        "dateCaption": "Время",
        "datesCaption": "Время",
        "subjectCaption": "Название",
        "startTimeCaption": "Начало",
        "endTimeCaption": "Окончание",
        "allDayEventCaption": "Весь день",
        "reminderCaption": "Напоминание",
        "detailsCaption": "Подробности",
        "contactsCaption": "Контакты",
        "todayCaption": "сегодня",
        "locationCaption": "Место",
        "patternCaption": "Повторение",
        "rangeCaption": "Период повторения",
        "everyCaption": "каждый",
        "ofEveryCaption": "каждого",
        "startCaption": "с",
        "noEndCaption": "без окончания",
        "endAfterCaption": "повторения",
        "endDateCaption": "до",
        "saveButtonCaption": "Сохранить",
        "optionsButtonCaption": "Подробности",
        "cancelButtonCaption": "Отмена",
        "recurrenceButtonCaption": "Повторения",
        "deleteButtonCaption": "Удалить",
        "secondsValue": "секунд",
        "minuteValue": "минута",
        "minutesValue": "минут",
        "hourValue": "час",
        "hoursValue": "часа",
        "dayValue": "день",
        "daysValue": "дней",
        "weeksValue": "недели",
        "monthValue": "месяца",
        "dailyValue": "В день",
        "weeklyValue": "В неделю",
        "monthlyValue": "В месяц",
        "yearlyValue": "В год",
        "intervalValue": "С интервалом",
        "firstValue": "первый",
        "secondValue": "второй",
        "thirdValue": "третий",
        "fourthValue": "четвертый",
        "lastValue": "последний",
        "weekendValue": "выходной день",
        "weekdayValue": "рабочий день",
        "recurrenceDailyOnePattern": "Повторяется каждый день",
        "recurrenceDailyTwoPattern": "Повторяется каждые [Days] дней",
        "recurrenceDailyThreePattern": "Повторяется каждый рабочий день",
        "recurrenceDailyFourPattern": "Повторяется каждый выходной день",
        "recurrenceWeeklyOnePattern": "Повторяется каждый [DaysOfWeek]",
        "recurrenceWeeklyTwoPattern": "Повторяется каждую [Weeks] неделю в [DaysOfWeek]",
        "recurrenceMonthlyOnePattern": "Повторяется каждого [DayOfMonth] числа каждого [Months] месяца",
        "recurrenceMonthlyTwoPattern": "Повторяется каждого [Occurrence] [Day] каждого [Months] месяца",
        "recurrenceYearlyOnePattern": "Повторяется каждого [DayOfMonth] [MonthOfYear]",
        "recurrenceYearlyTwoPattern": "Повторяется каждого [Occurrence] [Day] каждого [MonthOfYear]",
        "recurrenceIntervalPattern": "Повторяется с интервалом [Interval.Days] дней [Interval.Hours] часа [Interval.Minutes] минут [Interval.Seconds] секунд",
        "recurrenceStartDatePattern": "с [StartDate]",
        "recurrenceEndDatePattern": "до [EndDate]",
        "recurrenceTimeOnePattern": "с [StartTime] до [EndTime]",
        "recurrenceTimeTwoPattern": "в [StartTime]"
    }
}